import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { useEffect } from "react";
import { styled } from "styled-components";

import CharactersPageComponent from "@/components/CharactersPage.component";
import Pagination from "@/components/Pagination.component";
export default function Home() {
    return (
        <>
            <Head>
                <title>GOT books & characters</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
            </Head>
            <main className={styles.main}>
                <Container>
                    <h1>Liste des personnages de Game Of Thrones</h1>
                    <CharactersPageComponent></CharactersPageComponent>
                </Container>
            </main>
        </>
    );
}

const Container = styled.li`
    margin: 20px 0;
    border: solid lightGrey 1px;
    border-radius: 5px;
    list-style: none;
    padding: 20px;
    max-width: 900px;
    margin: 0 auto;
`;
