import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { useEffect } from "react";

import CharactersListComponent from "components/CharactersList.component";
export default function Home() {
    return (
        <>
            <Head>
                <title>GOT books & characters</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                {/* <link rel="icon" href="/favicon.ico" />  */}
            </Head>
            <main className={styles.main}>
                <CharactersListComponent></CharactersListComponent>
            </main>
        </>
    );
}
