import Head from "next/head";
import Link from "next/link";

const Home = () => {
    return (
        <>
            <Head>
                <title>GOT books & characters</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
            </Head>
            <main>
                <Link href="/books">Voir les livres</Link>
                <Link href="/characters">Voir les personnages</Link>
            </main>
        </>
    );
};

export default Home;
